"""add template header_mapping and service header_media

Revision ID: 17359cd13d6b
Revises: 78ca3dc09f0e
Create Date: 2026-08-10 10:48:55.163287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '17359cd13d6b'
down_revision: Union[str, None] = '78ca3dc09f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('header_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('whatsapp_templates', sa.Column('header_mapping', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_templates', 'header_mapping')
    op.drop_column('services', 'header_media')
    # ### end Alembic commands ###
