"""add_api_keys_and_survey_profiles

Revision ID: 56e1524f310e
Revises: dd55d9deed69
Create Date: 2026-06-12 16:03:23.913516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '56e1524f310e'
down_revision: Union[str, None] = 'dd55d9deed69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('notify_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_api_keys_api_key'), 'company_api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_company_api_keys_company_id'), 'company_api_keys', ['company_id'], unique=False)
    op.create_table('survey_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('external_profile_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'external_profile_id', name='uq_survey_profile_company_extid')
    )
    op.create_index(op.f('ix_survey_profiles_company_id'), 'survey_profiles', ['company_id'], unique=False)
    op.create_table('survey_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('external_question_id', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(length=20), nullable=False),
    sa.Column('button_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['survey_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'order_index', name='uq_survey_question_profile_order')
    )
    op.create_index(op.f('ix_survey_questions_profile_id'), 'survey_questions', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_questions_profile_id'), table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_index(op.f('ix_survey_profiles_company_id'), table_name='survey_profiles')
    op.drop_table('survey_profiles')
    op.drop_index(op.f('ix_company_api_keys_company_id'), table_name='company_api_keys')
    op.drop_index(op.f('ix_company_api_keys_api_key'), table_name='company_api_keys')
    op.drop_table('company_api_keys')
    # ### end Alembic commands ###
