"""add broadcast campaigns recipients optouts invalid numbers

Revision ID: 78ca3dc09f0e
Revises: dbdd298a422e
Create Date: 2026-08-04 15:50:47.820163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '78ca3dc09f0e'
down_revision: Union[str, None] = 'dbdd298a422e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('mobile_no', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'mobile_no', name='uq_invalid_company_mobile')
    )
    op.create_index(op.f('ix_invalid_numbers_company_id'), 'invalid_numbers', ['company_id'], unique=False)
    op.create_table('messaging_optouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('mobile_no', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'mobile_no', name='uq_optout_company_mobile')
    )
    op.create_index(op.f('ix_messaging_optouts_company_id'), 'messaging_optouts', ['company_id'], unique=False)
    op.create_table('broadcast_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('param_mode', sa.String(length=20), nullable=False),
    sa.Column('shared_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stop_on_error', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('read', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_campaigns_company_id'), 'broadcast_campaigns', ['company_id'], unique=False)
    op.create_index(op.f('ix_broadcast_campaigns_status'), 'broadcast_campaigns', ['status'], unique=False)
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('mobile_no', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('skip_reason', sa.String(length=40), nullable=True),
    sa.Column('wamid', sa.String(length=200), nullable=True),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['broadcast_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'mobile_no', name='uq_broadcast_recipient_campaign_mobile')
    )
    op.create_index('ix_broadcast_recipients_campaign_status', 'broadcast_recipients', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_broadcast_recipients_mobile_no', 'broadcast_recipients', ['mobile_no'], unique=False)
    op.create_index('ix_broadcast_recipients_wamid', 'broadcast_recipients', ['wamid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_broadcast_recipients_wamid', table_name='broadcast_recipients')
    op.drop_index('ix_broadcast_recipients_mobile_no', table_name='broadcast_recipients')
    op.drop_index('ix_broadcast_recipients_campaign_status', table_name='broadcast_recipients')
    op.drop_table('broadcast_recipients')
    op.drop_index(op.f('ix_broadcast_campaigns_status'), table_name='broadcast_campaigns')
    op.drop_index(op.f('ix_broadcast_campaigns_company_id'), table_name='broadcast_campaigns')
    op.drop_table('broadcast_campaigns')
    op.drop_index(op.f('ix_messaging_optouts_company_id'), table_name='messaging_optouts')
    op.drop_table('messaging_optouts')
    op.drop_index(op.f('ix_invalid_numbers_company_id'), table_name='invalid_numbers')
    op.drop_table('invalid_numbers')
    # ### end Alembic commands ###
