"""add phonebooks and phonebook_contacts

Revision ID: dbdd298a422e
Revises: 5520e93a05af
Create Date: 2026-07-31 16:00:50.556701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbdd298a422e'
down_revision: Union[str, None] = '5520e93a05af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonebooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_phonebook_company_name')
    )
    op.create_index(op.f('ix_phonebooks_company_id'), 'phonebooks', ['company_id'], unique=False)
    op.create_table('phonebook_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phonebook_id', sa.UUID(), nullable=False),
    sa.Column('mobile_no', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['phonebook_id'], ['phonebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phonebook_id', 'mobile_no', name='uq_phonebook_contact_mobile')
    )
    op.create_index(op.f('ix_phonebook_contacts_mobile_no'), 'phonebook_contacts', ['mobile_no'], unique=False)
    op.create_index(op.f('ix_phonebook_contacts_phonebook_id'), 'phonebook_contacts', ['phonebook_id'], unique=False)
    # ### end Alembic commands ###

    # This resource was briefly called "broadcast_lists" before it shipped. No
    # deployed database ever had those rows, but an environment where someone
    # granted the permission by hand would silently lose access, so rename them.
    op.execute(
        "UPDATE role_page_permission SET page_name = 'phonebooks' "
        "WHERE page_name = 'broadcast_lists'"
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM role_page_permission WHERE page_name = 'phonebooks'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phonebook_contacts_phonebook_id'), table_name='phonebook_contacts')
    op.drop_index(op.f('ix_phonebook_contacts_mobile_no'), table_name='phonebook_contacts')
    op.drop_table('phonebook_contacts')
    op.drop_index(op.f('ix_phonebooks_company_id'), table_name='phonebooks')
    op.drop_table('phonebooks')
    # ### end Alembic commands ###
